# docker-compose.yml
version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app   # remove in production; useful for local dev
    environment:
      - MODEL_PATH=model/heart_model.joblib
